version: '3.1'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - dmz_network
    volumes:
      - ./default.conf:etc/nginx/conf.d/default.conf
  web:
    image: nginx:alpine
    ports:
      - 5000:5000
    networks:
      - dmz_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - mz_network
  
  firewall_dmz:
    image: ubuntu
    networks:
      - dmz_network
  
  firewall_mz:
    image: ubuntu
    networks:
      - mz_network

  client1:
    image: alpine
    networks:
      - mz_network
  client2:
    image: alpine
    networks:
      - mz_network

networks:
  dmz_network:
    driver: bridge
  mz_network:
    driver: bridge

