version: '3.8'

services:
  reverse-proxy:
    image: "traefik:v2.10"
    restart: always
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Dashboard di Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Accesso a Docker per l'autodiscovery
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"      # Configurazione di Traefik
    networks:
      - dmz_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - mz_network
    restart: always

  
  firewall_dmz:
    image: ubuntu
    cap_add:
      - NET_ADMIN  
      - NET_RAW    
    networks:
      - dmz_network
        # ipv4_address: 192.168.200.1
    volumes:
      - ./dmz_firewall.sh:/usr/local/bin/dmz_firewall.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/dmz_firewall.sh"]
    restart: always

  
  firewall_mz:
    image: ubuntu
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - mz_network
        # ipv4_address: 192.168.100.1
    volumes:
      - ./mz_firewall.sh:/usr/local/bin/mz_firewall.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/mz_firewall.sh"]
    restart: always

  client1:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - mz_network
    restart: always
  client2:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - mz_network
    restart: always
  client3:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - dmz_network
    restart: always


networks:
  #rete interna alla parte privata del sistema
  mz_internal:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"  # IP del firewall_mz
  
  dmz_internal:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/16"
          gateway: "172.19.0.1"  # IP del firewall_dmz
 
  dmz_network:
    driver: bridge
 
  mz_network:
    driver: bridge

